### ISSUE TITLE
What's your plan for releasing this dataset

### ISSUE THREAD

**Issue by GaryYufei** [dayihengliu/KeyMultiHeadline#1]
Hi, thanks for your great work! I am just wondering if you have any concrete plan of releasing this dataset?

**Comment by dayihengliu** [comment]
> Hi, thanks for your great work! I am just wondering if you have any concrete plan of releasing this dataset?

Thanks for your attention to our work. The dataset and source code is available now.

**Comment by GaryYufei** [comment]
Thanks for this!
