### ISSUE TITLE
Any Implementation for Training Seq2seq and Slot Tagging Model

### ISSUE THREAD

**Issue by riven314** [dayihengliu/KeyMultiHeadline#2]
Great work!
The paper mentioned trained Seq2seq and Slot Tagging are used for keyphrases generation.
Will you include related implementation (model architecture, training and inference ... etc.) into your repo?

**Comment by dayihengliu** [comment]
> Great work!
> The paper mentioned trained Seq2seq and Slot Tagging are used for keyphrases generation.
> Will you include related implementation (model architecture, training and inference ... etc.) into your repo?

We updated the readme about keyphrases generation. Please refer to https://github.com/dayihengliu/KeyMultiHeadline/blob/master/README.md#keyphrase-generation

**Comment by riven314** [comment]
Thank you for the prompt reply! I will try it out
